### ISSUE TITLE
Use autorandr

### ISSUE THREAD

**Issue by ramnes** [ramnes/qtile-config#3]
https://github.com/phillipberndt/autorandr

**Comment by TauPan** [comment]
I think you already fixed that. ;)

However I've just had a problem changing an existing autorandr configuration (via arandr) because qtile would detect it as a change and automatically reload the existing config.

I came up with this as a remedy:
```python
@hook.subscribe.screen_change
def set_screens(qtile, event):
    if not os.path.exists(os.path.expanduser('~/NO-AUTORANDR')):
        subprocess.run(["autorandr", "--change"])
        qtile.cmd_restart()
```

Maybe there's a more graceful way to do it though.

**Comment by ramnes** [comment]
I did fix that, indeed!

You problem is interesting, I'm not sure how I didn't encounter this before. Maybe I simply commented this hook when I was trying some new configurations.

I guess a cleaner solution would be to inspect events and only run `autorandr` when it makes sense. I need to look deeper into this but I think it's possible to differentiate an event originated by `arandr` from one due to a monitor being plugged or unplugged.

**Comment by TauPan** [comment]
> You problem is interesting, I'm not sure how I didn't encounter this before. Maybe I simply commented this hook when I was trying some new configurations.

Which would mean restarting qtile for that purpose. Ok, I guess.

> I guess a cleaner solution would be to inspect events and only run `autorandr` when it makes sense. I need to look deeper into this but I think it's possible to differentiate an event originated by `arandr` from one due to a monitor being plugged or unplugged.

I think arandr just executes xrandr, but I'm not sure if that makes any difference.

**Comment by ramnes** [comment]
It does indeed, but I think we can guess from an event if it's just a layout change or a physical change.

**Comment by ramnes** [comment]
Another way could be to check if there's a `arandr` process running or not, but I couldn't find a clean way to do this with the standard library. It's pretty simple with psutil, though...

**Comment by TauPan** [comment]
> Another way could be to check if there's a `arandr` process running or not, but I couldn't find a clean way to do this with the standard library. It's pretty simple with psutil, though...

This is probably the most elegant way, i.e. `pgrep -f arandr`. This won't work for users that prefer other tools, but who would ever want to use anything else than arandr ;)

**Comment by ramnes** [comment]
Ah! I know why I never encountered this problem. It's because autorandr doesn't do anything if it doesn't find a matching profile. Which means that if you don't want this to happen, you just have to delete the profile it matches. Which makes sense!

**Comment by TauPan** [comment]
Ah ok. I occasionally want to change a configuration, but it happens rarely. Thanks for the conversation, even though this should have been closed long ago ;)
