### ISSUE TITLE
What's your approach to installing qtile from HEAD before you install your dots?

### ISSUE THREAD

**Issue by jgarte** [ramnes/qtile-config#5]
Hi,

What's your approach to installing qtile from `HEAD` before you install your `config.py`?

https://github.com/ramnes/qtile-config#install

**Comment by ramnes** [comment]
I install from git and run `git pull` regularly :)

**Comment by jgarte** [comment]
Hi, thanks for the reply.

Do you do that in a `venv` or without `venv`?

One workflow I was thinking of, for example:

```sh
git clone ...
cd qtile
python -m venv .venv
source .venv/bin/activate
pip install .
```

**Comment by ramnes** [comment]
Both work and it's really just personal preference – I don't use a virtualenv for my "main" installation but I did run Qtile in a virtualenv for specific branches in the past
